<?php

class AdminController extends BaseController
{
    /**
     * Action name
     * @var string
     */
    public $name = 'index';

    /**
     * @var ArticleRepository
     */
    protected $adminProfile;

    public function __construct(AdminRootProfile $adminRootProfile)
    {
        $this->adminProfile = $adminRootProfile;
    }

    protected function render($templateName, $vars = [])
    {
        return parent::render($templateName, $vars); // TODO: Change the autogenerated stub
    }

    public function admAction(Request $request)
    {
        if ($this->adminProfile->adminAuth($_COOKIE["pAccount"]))
        {
            return new Response(
                $this->render('admin/main',[
                    'title' => 'Панель администратора',
                    'msg' => "Вы вошли в панель админинстратора"
                ])
            );
        }
        return new Response(
            $this->render('main', [
                'title' => 'Основная страница',
                'text' => '',
                'error' => 'Нет доступа к разделу'
            ]));
    }
    public function createUserFormAction(Request $request)
    {
        if ($this->adminProfile->adminAuth($_COOKIE["pAccount"]))
        {
            return new Response(
                $this->render('admin/form/createUserForm', [
                    'title' => 'Создание Пользователя',
                    'formName' => '/Название формы/'
                ]));
        }
        return new Response(
            $this->render('main', [
                'title' => 'Основная страница',
                'text' => '',
                'error' => 'Нет доступа к разделу'
            ]));
    }

    public function newUserAction(Request $request)
    {
        if ($this->adminProfile->adminAuth($_COOKIE["pAccount"]))
        {
            if ($request->isPost() && $request->getQueryParameterUser('newUser'))
            {
                print_r("TEST");
                die;
            }
            return new Response('/admin', '301', 'adminHome');
        }
        return new Response(
            $this->render('main', [
                'title' => 'Основная страница',
                'text' => '',
                'error' => 'Нет доступа к разделу'
            ]));
    }
}


//if ($this->adminProfile->adminAuth($_COOKIE["pAccount"]))
//{
//    BODY :::::
//}
//return new Response(
//    $this->render('main', [
//        'title' => 'Основная страница',
//        'text' => '',
//        'error' => 'Нет доступа к разделу'
//    ]));