<?php

class IndexController extends BaseController
{
    /**
     * Action name
     * @var string
     */
    public $name = 'index';

    /**
     * @var ArticleRepository
     */
    protected $articleRepository;

    public function __construct(ArticleRepository $articleRepository)
    {
        $this->articleRepository = $articleRepository;
    }

    protected function render($templateName, $vars = [])
    {
        return parent::render($templateName, $vars); // TODO: Change the autogenerated stub
    }

    public function indexAction(Request $request)
    {
        return new Response(
            $this->render('main', [
                '/' => []
            ])
        );
    }

    public function showAction(Request $request)
    {
        $id = $request->getQueryParameter("id");

        $article = is_numeric($id) ? $this->articleRepository->getById($id) : null;

        if ($article === null) {
            return new Response('Page not found <br><a href="/">back to articles list</a>',
                '404', 'Not found');
        }

        return new Response(
            $this->render('article', [
                'article' => $article
            ])
        );
    }

    public function loginAction(Request $request) {
        return new Response(
            $this->render('auth/login', [
            'title' => 'login page',
            'text' => ''
        ]));
    }

    /**
     * Возращает значение страницы аунтефекации.
    **/
    public function authAction(Request $request)
    {

        $pAccount = sprintf("%s", $_POST['login']);
        $password = sprintf("%s", $_POST['password']);

        setcookie('pAccount', $pAccount);
        setcookie('password', $password);
        return new Response('/', '301', 'homePage');
    }

    public function registrAction(Request $request) {
        return new Response(
            $this->render('auth/registr', [
            'title' => 'registr page',
            'text' => ''
        ]));
    }

    public function addInfoAction(Request $request) {
        return new Response(
            $this->render('changeInfo', [
            'title' => 'changeInfo page',
            'text' => ''
        ]));
    }

    public function addAction(Request $request) {
        if ($request->isPost() && !empty($request->getRequestParameter('counters')))
        {
            $counters = $request->getRequestParameter('counters');
            foreach ($counters as $key => $value)
            {
                /* механизм получения id счетчика из информации авторизованного пользовеля*/
                $this->articleRepository->add();
            }
            /* Тут надо указать все перменные из метода POST котор https://i.imgur.com/muDUqbY.png ые будут добавлятся в sql
             В данный момент. 1) 3 Счётчтчика ГВС ХВС, ЕЛЕ ,
            которые указывают инфолрмацию ввиде простого числа.
            2) Перебрать через цикл foreach, и отправить по отдельности их.
            3) Информацию о типе счетчика хранится в таблице counters*/
        }
        return new Response('/', '301', 'homePage');
    }
}